FROM continuumio/anaconda3:2020.07

ADD app /host/app
WORKDIR /host/app

RUN conda create -n estnltk python=3.5 anaconda

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "estnltk", "/bin/bash", "-c"]

RUN conda install -c estnltk -c conda-forge estnltk

RUN conda env list

ENTRYPOINT ["python3", "entrypoint.py"]